### ISSUE TITLE
[LineageOS 19.1] Headphones not working on device with Unisoc processor

### ISSUE THREAD

**Issue by Artem13327** [AndyCGYan/lineage_patches_unified#9] opened 2023-09-01 18:44 UTC

**Comment by Fraynlls** [comment] 2024-02-10 15:07
the problem is not solved, I need help, I would really like it to be solved for the realme c21y phone unisoc tiger t610 logcat
[logcat.txt](https://github.com/AndyCGYan/lineage_patches_unified/files/14229625/logcat.txt)

**Comment by Fraynlls** [comment] 2024-02-10 15:09
and on Android 13-14 there is a problem with video playback, color inversion, also in the camera
![Screenshot_20240210-105855_YouTube](https://github.com/AndyCGYan/lineage_patches_unified/assets/70051752/16e532f9-5173-442a-98c4-8e23ef075a00)

**Comment by AndyCGYan** [comment] 2024-05-19 02:21
As I only intended GitHub to host code, I'm scrubbing all open issues and closing the Issues section.

If you have an unresolved issue, please move to XDA, but do follow appropriate reporting procedures (most importantly, test on TD-AOSP in parallel).

**Closed by AndyCGYan** 2024-05-19 02:21 UTC
